spring:
    datasource:
        url: jdbc:mysql://192.168.238.150/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
        username: root
        password: root
        hikari:
            max-lifetime: 1800000
            connection-timeout: 5000
            idle-timeout: 3600000
            max-pool-size: 12
            min-idle: 4
            connection-test-query: /**ping*/