////
http://sivalabs.in/2016/03/springboot-working-with-jdbctemplate/
////
:toc:
:icons: font
:source-highlighter: prettify
:image-width: 500
:base-root: .

=== spring boot 与 JdbcTemplate 一起工作

本文将介绍如何将spring boot 与 JdbcTemplate一起工作。

Spring对数据库的操作在jdbc上面做了深层次的封装，使用spring的注入功能，可以把DataSource注册到JdbcTemplate之中。
JdbcTemplate 是在JDBC API基础上提供了更抽象的封装，并提供了基于方法注解的事务管理能力。
通过使用SpringBoot自动配置功能并代替我们自动配置beans.
在maven中，我们需要增加spring-boot-starter-jdbc模块
[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jdbc</artifactId>
</dependency>
----
通过这个模块为我们做了以下几件事

* tomcat-jdbc－{version}.jar为我们自动配置DataSource.
* 如果你没有定义任何DataSource，SpringBoot将会自动配置一个内存的数据库资源设置
* 如果没有设置任一个beans，SpringBoot会自动注册它
* 初始化数据库

    如果我们在classpath里定义了schema.sql和data.sql文件，springBoot将会使用这些文件自动初始化数据库(但你必须选建库)
    除了载入schema.sql和data.sql外，SpringBoot也会载入schema-${platform}.sql和data-${platform}.sql，如果在你的classpath下存在的话。

            spring.datasource.schema=xxxx-db.sql 可以定义你的建库文件
            spring.datasource.data=xxxx-data.sql  可以定义你的数据文件
            spring.datasource.initialize＝true|false 可以决定是不是要初始化这些数据库文件
            spring.datasource.continueOnError＝true|false 有了错误是否继续运行

## 定义数据库驱动信息

`/src/main/resources/application.yml`
[source]
----
include::{base-root}/src/main/resources/application.yml[]
----

其中
[source]
----
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gs-jdbc
    username: root
    password:
----
我是用的mysql,你也可以定义其它或者不定义，如果不定义，springBoot会自动为我们配置一个嵌入的数据库( Embedded database)

## 自定义数据源

如果你不想用默认的配置数据源，如你想用阿里巴巴的数据池管理数据源，你也可以自己配置

先排除tomcat-jdbc的默认配置dataSource

[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jdbc</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-jdbc</artifactId>
        </exclusion>
    </exclusions>
</dependency>
----

定义自己的数据资源
这里使用了阿里巴巴的数据池管理,你也可以使用BasicDataSource
[source,xml]
----
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid</artifactId>
    <version>1.0.19</version>
</dependency>
----
`/src/main/java/com/example/SpringBootJdbcDemoApplication.java`
[source]
----
include::{base-root}/src/main/java/com/example/SpringBootJdbcDemoApplication.java[]
----

你也可以用别的：
[source,xml]
----
<dependency>
    <groupId>commons-dbcp</groupId>
    <artifactId>commons-dbcp</artifactId>
    <version>1.4</version>
</dependency>
----

[source,java]
----
    @Bean
    public DataSource dataSource() {
        BasicDataSource dataSource = new BasicDataSource();
        dataSource.setDriverClassName(env.getProperty("spring.datasource.driver-class-name"));
        dataSource.setUrl(env.getProperty("spring.datasource.url"));
        dataSource.setUsername(env.getProperty("spring.datasource.username"));
        dataSource.setPassword(env.getProperty("spring.datasource.password"));
        return dataSource;
    }
----

## 创建实体对象
`/src/main/java/com/example/domain/User.java`
[source]
----
include::{base-root}/src/main/java/com/example/domain/User.java[]
----

## 创建持久层
有了上面的数据源配置，我们可以注入JdbcTemplate到数据访问组件并与数据库交互。
`/src/main/java/com/example/repositories/UserRepository.java`
[source]
----
include::{base-root}/src/main/java/com/example/repositories/UserRepository.java[]
----
你或许己注意到，大多数时候，我们都在应用中做这些配置的事。

## 创建单元测试测试我们的持久层方法
`/src/test/java/SpringBootJdbcDemoApplicationTests.java`
[source]
----
include::{base-root}/src/test/java/SpringBootJdbcDemoApplicationTests.java[]
----

源代码请访问：  https://github.com/tomlxq/best-practice/tree/master/gs-jdbc[https://github.com/tomlxq/best-practice/tree/master/gs-jdbc]







