spring:
  datasource:
    url: jdbc:mysql://192.168.238.150:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&serverTimeZone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置逻辑删除  1 删除  0 未删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0