:toc:
:icons: font
:source-highlighter: prettify
:image-width: 500
:base-root: .
////
Java注解教程及自定义注解 http://www.importnew.com/17413.html
Java注解处理器 http://www.importnew.com/15246.html
HOW ANNOTATIONS WORK IN JAVA ? http://idlebrains.org/tutorials/java-tutorials/how-annotations-work-java/
跟开涛学SpringMVC http://www.importnew.com/19543.html
Java注解实践 http://www.importnew.com/17524.html
Java中的注解是如何工作的？ http://www.importnew.com/10294.html
////
= 什么是注解？

用一个词就可以描述注解，那就是元数据，即一种描述数据的数据。所以，可以说注解就是源代码的元数据。

`/src/main/java/override/Animal.java`
[source,java]
----
include::{base-root}/src/main/java/override/Animal.java[]
----

`/src/main/java/override/Fish.java`
[source,java]
----
include::{base-root}/src/main/java/override/Fish.java[]
----
上面的代码中，我重写了eat()方法并使用了@Override注解。但是，即使我不使用@Override注解标记代码，程序也能够正常执行。那么，该注解表示什么？这么写有什么好处吗？事实上，@Override告诉编译器这个方法是一个重写方法(描述方法的元数据)，如果父类中不存在该方法，编译器便会报错，提示该方法没有重写父类中的方法。现在我们了解了什么是注解，并且使用注解有助于阅读程序。

                如本例中如果父类中没有eat()方法，测试时会有这样的错误提示
                Error:(5, 5) java: 方法不会覆盖或实现超类型的方法

Annotation是一种应用于类、方法、参数、变量、构造器及包声明中的特殊修饰符。它是一种由JSR-175标准选择用来描述元数据的一种工具。
Annotation(注解)，其实就是对类，方法，属性进行的一种标示，一种注释（注意，这个里注释不是为了让我们开发或维护人员阅读更方便，而是为JVM看呢），通过这些标示，Java虚拟机可以完成这些标示对应的功能。例如使用框架开发时，我们都是通过配置文件进行对象关系组合映射等功能，而通过注解我们可以完全代替配置文件的编写。

查看例子
[source,java]
----
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.SOURCE)
public @interface Override {
}
----

    @interface用来声明一个注解，其中的每一个方法实际上是声明了一个配置参数。方法的名称就是参数的名称，返回值类型就是参数的类型（返回值类型只能是基本类型、Class、String、enum）。可以通过default来声明参数的默认值。

对于@Override注释你可能有些疑问，它什么都没做，那它是如何检查在父类中有一个同名的函数呢。@Override注解的定义不仅仅只有这么一点代码。
Annotations仅仅是元数据，和业务逻辑无关。理解起来有点困难，但就是这样。如果Annotations不包含业务逻辑，那么必须有人来实现这些逻辑。元数据的用户来做这个事情。Annotations仅仅提供它定义的属性(类/方法/包/域)的信息。Annotations的用户(同样是一些代码)来读取这些信息并实现必要的逻辑。

当我们使用Java的标注Annotations(例如@Override)时，JVM就是一个用户，它在字节码层面工作。到这里，应用开发人员还不能控制也不能使用自定义的注解。

= 为什么要引入注解？

使用Annotation之前(甚至在使用之后)，XML被广泛的应用于描述元数据。不知何时开始一些应用开发人员和架构师发现XML的维护越来越糟糕了。他们希望使用一些和代码紧耦合的东西，而不是像XML那样和代码是松耦合的(在某些情况下甚至是完全分离的)代码描述。如果你在Google中搜索“XML vs. annotations”，会看到许多关于这个问题的辩论。最有趣的是XML配置其实就是为了分离代码和配置而引入的。上述两种观点可能会让你很疑惑，两者观点似乎构成了一种循环，但各有利弊。下面我们通过一个例子来理解这两者的区别。

假如你想为应用设置很多的常量或参数，这种情况下，XML是一个很好的选择，因为它不会同特定的代码相连。如果你想把某个方法声明为服务，那么使用Annotation会更好一些，因为这种情况下需要注解和方法紧密耦合起来，开发人员也必须认识到这点。

另一个很重要的因素是Annotation定义了一种标准的描述元数据的方式。在这之前，开发人员通常使用他们自己的方式定义元数据。例如，使用标记interfaces，注释，transient关键字等等。每个程序员按照自己的方式定义元数据，而不像Annotation这种标准的方式。

目前，许多框架将XML和Annotation两种方式结合使用，平衡两者之间的利弊。

**Annotation的作用:**

* 编写文档：通过代码里标识的元数据生成文档。

* 代码分析：通过代码里标识的元数据对代码进行分析。

* 编译检查：通过代码里标识的元数据让编译器能实现基本的编译检查。

= JDK内置的几个常用注解：
* @Documented —— 指明拥有这个注解的元素可以被javadoc此类的工具文档化。这种类型应该用于注解那些影响客户使用带注释的元素声明的类型。如果一种声明使用Documented进行注解，这种类型的注解被作为被标注的程序成员的公共API。

* @Target——指明该类型的注解可以注解的程序元素的范围。该元注解的取值可以为TYPE,METHOD,CONSTRUCTOR,FIELD等。如果Target元注解没有出现，那么定义的注解可以应用于程序的任何元素。

            @Target 表示该注解用于什么地方，可能的值在枚举类 ElemenetType 中，包括：
            ElemenetType.CONSTRUCTOR----------------------------构造器声明
            ElemenetType.FIELD --------------------------------------域声明（包括 enum 实例）
            ElemenetType.LOCAL_VARIABLE------------------------- 局部变量声明
            ElemenetType.METHOD ----------------------------------方法声明
            ElemenetType.PACKAGE --------------------------------- 包声明
            ElemenetType.PARAMETER ------------------------------参数声明
            ElemenetType.TYPE--------------------------------------- 类，接口（包括注解类型）或enum声明

* @Inherited——指明该注解类型被自动继承。如果用户在当前类中查询这个元注解类型并且当前类的声明中不包含这个元注解类型，那么也将自动查询当前类的父类是否存在Inherited元注解，这个动作将被重复执行知道这个标注类型被找到，或者是查询到顶层的父类。允许子类继承父类中的注解

* @Retention——指明了该Annotation被保留的时间长短。RetentionPolicy取值为SOURCE,CLASS,RUNTIME。

            @Retention 表示在什么级别保存该注解信息。可选的参数值在枚举类型 RetentionPolicy 中，包括：
            RetentionPolicy.SOURCE ---------------------------------注解将被编译器丢弃
            RetentionPolicy.CLASS -----------------------------------注解在class文件中可用，但会被VM丢弃
            RetentionPolicy.RUNTIME VM-------将在运行期也保留注释，因此可以通过反射机制读取注解的信息。

= Java提供了三种内建注解。

* @Override——当我们想要复写父类中的方法时，我们需要使用该注解去告知编译器我们想要复写这个方法。这样一来当父类中的方法移除或者发生更改时编译器将提示错误信息。

* @Deprecated——当我们希望编译器知道某一方法不建议使用时，我们应该使用这个注解。Java在javadoc 中推荐使用该注解，我们应该提供为什么该方法不推荐使用以及替代的方法。此注解是对不应该，或者将要淘汰的方法进行标识，当编程人员使用时就会给予提示。这个功能在一些基础jar包，规范，框架等的中我们经常可以看到，还保留这些方法是为了兼容前边的一些版本，有一过度的阶段。看下边的这种效果应该都见过：

* @SuppressWarnings——这个仅仅是告诉编译器忽略特定的警告信息，例如在泛型中使用原生数据类型。它的保留策略是SOURCE（译者注：在源文件中有效）并且被编译器丢弃。此注解表示去除一些警告，但是里边需要我们制定参数

> 再次强调下元注解是java API提供，是专门用来定义注解的注解.





注解方式开发

优点

1，遵循OCP开发原则，修改配置文件即可进行功能扩展

2，集中管理对象和对象之间的组合关系，易于阅读

1，开发速度快

2，编译期间容易发现错误的出处

缺点

1，开发速度相对较慢；

2，编译时很难检查出错误，运行中的错误很难定位，调试难度较大。

1，管理分散，基本每个类上都有；

2，扩展功能时，没有遵循OCP开发原则。

何时选择

如果客户需求进行发生变化，那么采用配置文件的方式会好一些。有利于扩展。

如果客户需求不会频繁发生变化。那么使用注解非常好，开发效率快

最后提醒下：

1. 要用好注解，必须熟悉java 的反射机制，从上面的例子可以看出，注解的解析完全依赖于反射。

2. 不要滥用注解。平常我们编程过程很少接触和使用注解，只有做设计，且不想让设计有过多的配置时

= References:

* http://www.importnew.com/15246.html[Java注解处理器]
* http://www.yq1012.com/myweb/2230.html[注解是什么，为什么要使用注解]
* http://www.hongyanliren.com/2014m11/19591.html[Annotation 注解开发介绍优势 与好处java为什么采用注解开发]
* http://idlebrains.org/tutorials/java-tutorials/how-annotations-work-java/[HOW ANNOTATIONS WORK IN JAVA ?]
