logging:
  level:
    org.springframework: INFO
    ################### DataSource Configuration ##########################
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.238.150:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT
    username: root
    password: root
    initialize: true