logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
spring:
  # 配置日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #时间戳统一转换为指定格式
    time-zone: GMT+8  # 时区修改为东8区